// Freeze prevent the object from being mordified eith acciendanty or intentinally

export default Object.freeze({
  HOME_MAIN: "HomeScreen",
  SEARCH_MAIN: "SearchScreen",
  PROPERTY_ADD_MAIN: "PropertyEditingScreen",
  USER_CENTER_MAIN: "Account",
  WELCOME_AUTH: "Welcome",
  LOGIN_AUTH: "Login",
  REGISTER_AUTH: "Register",
  PROPERTY_LIST_PROP: "PropertyList",
  PROPERTY_DETAIL_PROP: "PropertyDetail",
  USER_CENTER_ACCOUNT: "UserCenter",
  USER_PROFILE_EDIT_ACCOUNT: "ProfileEdit",
  PROPERTIES_LOCATION: "PropertyLocations",
  USER_PROPERTIES: "UserProps",
  IMAGE_VIEW: "ImageView",
  TABS: "Tabs",
  AUTH: "Auth",
  PROPERTY_NAV: "PropNav",
  USER_NAV: "UserNav",
  HOUSE_LIST_SCREEN: "HouseListScreen",
  HOUSE_DETAIL_SCREEN: "HouseDetailScreen",
  HOUSES_NAV: "HousesNav",
});
